### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by momopanda123** [liznerski/fcdd#2] opened 2020-09-22 08:16 UTC
run_fmnist.py, run_cifar.py, run_tech.py... all runners have a Run out of input error.

====================================================================
...
File "C:\Users\KBM\.conda\envs\torch14\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ADFMNIST.__init__.<locals>.<lambda>'

(torch14) D:\90. Anormaly\fcdd>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\AIW_KBM\.conda\envs\torch14\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\AIW_KBM\.conda\envs\torch14\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
====================================================================

**Comment by liznerski** [comment] 2020-09-22 09:13
Unfortunately, I am not able to reproduce this. 
Can you give me some more information, i.e., the complete traceback (say for fmnist) and your OS?
It seems like you might have run the code on Windows. 
In the current version, the code is only tested on Linux. It might work on other OSs, but there are no guarantees.

**Comment by liznerski** [comment] 2020-10-23 14:29
We have reproduced the error on Windows and applied some fixes to get rid of it.
The error was due to pickle's inability to deal with lambda expressions in Windows. 
I pushed the fixes into the new branch 'windows' (https://github.com/liznerski/fcdd/tree/windows). 
You might give it a try. If you still encounter problems, feel free to report them here.  

P.S.: Thanks to @denix56 for locating the problem (#3).

**Comment by liznerski** [comment] 2021-02-11 10:33
I close this for now, as it seems to be fixed. Feel free to reopen if you still encounter problems.

**Comment by opentld** [comment] 2021-11-08 11:10
When I train the custom dataset, I get a run out of input error, I am sure I am using the windows branch.
python runners/run_foodata.py --dataset foodata --net FCDD_CNN224_VGG --datadir ../../data/datasets

![image](https://user-images.githubusercontent.com/21096515/140730687-d7ee467a-1a6c-40d5-bd8c-3f37bd7e8953.png)

argparse_configs.py: 
![image](https://user-images.githubusercontent.com/21096515/140730919-258979df-b849-4862-8fe3-89ea610d8c81.png)

foodata.py:
![image](https://user-images.githubusercontent.com/21096515/140731543-cebf0b40-3154-4f39-930f-71624167e756.png)

run_foodata.py:
![image](https://user-images.githubusercontent.com/21096515/140731669-db5da040-6556-4795-8834-160a984a6903.png)

@liznerski

**Comment by liznerski** [comment] 2021-11-09 09:04
There is a MVTec-AD specific implementation. Use [this](https://github.com/liznerski/fcdd/blob/master/python/fcdd/runners/run_mvtec.py) runner. The custom runner should probably also work if you set all configurations (including pre-processing) identically, but we've never tested this. 

The error in Windows seems again due to some problem with pickle. I will look into this.

**Comment by danielsoy** [comment] 2021-12-21 17:17
Hey there!

I would like to run windows version of mvtec.py.

But i could not install FCDD.

Which **right** is the pip command to install it?

Thanks you uso much!

**Closed** 2022-02-02 12:26 UTC
